name: 'Hello World'
description: 'Greet someone and record'
inputs:
  who-to-greet:
    description:
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greated you'
runs:
  using: 'node12'
  main: 'index.js'